# Create a DNS record
resource "cloudflare_record" "example_com" {
  zone_id = var.dns_zone_name
  name    = var.swa_custom_domain
  value   = var.swa_dns_auth_value # The value retrieved from Azure SWA custom domain
  type    = "TXT"
  ttl     = 3600
  proxied = false
}

resource "cloudflare_record" "example_com" {
  zone_id = var.dns_zone_name
  name    = var.swa_dns_auth_record
  value   = var.swa_dns_auth_value # The value retrieved from Azure SWA custom domain
  type    = "TXT"
  ttl     = 3600
  proxied = false
}

resource "cloudflare_record" "example_com" {
  zone_id = var.dns_zone_name
  name    = var.swa_custom_domain
  value   = "" # The value of the autogenerated domain in Azure SWA
  type    = "CNAME"
  ttl     = 3600
  proxied = false
}
